# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d538395e1d4ce97c7e221e5ac78f598bf045387e699470ada7c600b3d79e810f6706f8ae5d1382e4a6ad7a42b6cdf57e1cb7de7c1e66d430952018de86c5258

test:
  secret_key_base: 69ed35c3954f748cdf23bd7af9b09e32cecb473c44ac727b58623d3838f56c984d500edffef089d64768dd7a3a0d01207f2fd82d6f5af65945dc62daa6f7aec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
